# Generated by Django 6.0.7 on 2026-07-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('courier', 'Courier'), ('admin', 'Administrator')], default='buyer', max_length=20),
        ),
    ]
